name: mycpen github visitor

on:
  schedule:
    - cron: "0 17 11-31 * *"
    # - cron: "0 * * * *"
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  replace-time:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - name: checkout
        uses: actions/checkout@v2
      - uses: szenius/set-timezone@v1.0 # 设置执行环境的时区
        with:
          timezoneLinux: "Asia/Shanghai"
      # setup python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      # mycpen github visitor
      - name: mycpen github visitor
        run: |
          cd .github/scripts/
          # 
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          # 
          nohup bash -c 'for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done' &
          for i in {1..10000}; do bash mycpen-github-visitor.sh &> /dev/null; done
